import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import { Toaster } from "@/components/ui/toaster"
import { cn } from "@/lib/utils"
import "./globals.css";

import Header from '@/components/header/header';

export const titillium = Titillium_Web({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"]
});

export const metadata: Metadata = {
  title: "Nidera",
  description: "Generated by me",
};

// Following 3 lines to avoid fontawesome flash too large when loading. Place in the root file.
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background antialiased flex flex-col",
          titillium.className
        )}>
          <Header />
          <main className="flex flex-1 w-full">
            {children}
          </main>
          <Toaster />
        </body>
    </html>
  );
}
