import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import { Toaster } from "@/components/ui/toaster"
import { cn } from "@/lib/utils"
import "./globals.css";

import { Header } from '@/components/Header/Header';

export const titillium = Titillium_Web({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"]
});

export const metadata: Metadata = {
  title: "Nidera",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background antialiased",
          titillium.className
        )}>
          <Header />
          <main>
            {children}
          </main>
          <Toaster />
        </body>
    </html>
  );
}
