const tableData = [
  {
    id: 1,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: true,
    lotes: [
      {
        id: 106,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        sembrado: true,
      },
      {
        id: 107,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        sembrado: true,
      },
      {
        id: 108,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        sembrado: true,
      }
    ]
  },
  {
    id: 2,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Maiz tardio',
    estado: 'downloaded',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 3,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Maiz',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: true,
    lotes: [
      {
        id: 100,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        sembrado: true,
      },
      {
        id: 101,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        sembrado: true,
      },
      {
        id: 102,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        sembrado: true,
      }
    ]
  },
  {
    id: 4,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'results_available',
    creado: 'Rosmualdo Loaizaga',
    sembrado: true,
    lotes: [
      {
        id: 103,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        sembrado: true,
      },
      {
        id: 104,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        sembrado: true,
      },
      {
        id: 105,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        sembrado: true,
      }
    ]
  },
  {
    id: 5,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 6,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'sent',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 7,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Maiz Temprano',
    estado: 'sent',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 8,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 9,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Maiz',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 10,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
]

export {
  tableData
};