import type { Recomendacion } from '@/app/recomendacion/recomendacion';

const tableData: Recomendacion[] = [
  {
    id: 1,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'error',
    creado: 'Rosmualdo Loaizaga',
    sembrado: true,
    lotes: [
      {
        id: 106,
        nombre: 'Nombres Lots Uysi',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        indice: '18912',
        bolsas_totales: '87',
        sembrado: true,
      },
      {
        id: 107,
        nombre: 'Lote Sjuyhjolip 76',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        indice: '18912',
        bolsas_totales: '87',
        sembrado: true,
      },
      {
        id: 108,
        nombre: 'Lotes tium 87',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        indice: '18912',
        bolsas_totales: '87',
        sembrado: true,
      }
    ]
  },
  {
    id: 2,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Maiz tardio',
    estado: 'downloaded',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 3,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Maiz',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: true,
    lotes: [
      {
        id: 100,
        nombre: 'Tevasco Nesto',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        indice: '18912',
        bolsas_totales: '87',
        sembrado: true,
      },
      {
        id: 101,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        indice: '18912',
        bolsas_totales: '87',
        sembrado: true,
      },
      {
        id: 102,
        nombre: 'Tevasco Nesto',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        indice: '18912',
        bolsas_totales: '87',
        sembrado: true,
      }
    ]
  },
  {
    id: 4,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'results_available',
    creado: 'Rosmualdo Loaizaga',
    sembrado: true,
    lotes: [
      {
        id: 103,
        nombre: 'Defura Pol Fam',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        indice: '18912',
        bolsas_totales: '87',
        sembrado: true,
      },
      {
        id: 104,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        indice: '18912',
        bolsas_totales: '87',
        sembrado: true,
      },
      {
        id: 105,
        nombre: 'Nombre del lote',
        fecha: '24/12/12',
        hibrido: 'NSAO234BOWEQ234BKJSD1',
        superficie: '3000 ha',
        indice: '18912',
        bolsas_totales: '87',
        sembrado: true,
      }
    ]
  },
  {
    id: 5,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 6,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'sent',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 7,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Maiz Temprano',
    estado: 'sent',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 8,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 9,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Maiz',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
  {
    id: 10,
    cliente: 'Fortalezza SA',
    propiedad: 'San Martin',
    cantidad: 12,
    distribuidor: 'Nombre del Distribuidor',
    cultivo: 'Girasol',
    estado: 'processing',
    creado: 'Rosmualdo Loaizaga',
    sembrado: false,
  },
]

const fakeRecomendacion: Recomendacion = {
  id: 1,
  cliente: 'Fortalezza SA',
  propiedad: 'San Martin',
  cantidad: 12,
  distribuidor: 'Nombre del Distribuidor',
  cultivo: 'Girasol',
  estado: 'error',
  creado: 'Rosmualdo Loaizaga',
  sembrado: true,
  lotes: [
    {
      id: 106,
      nombre: 'Nombres Lots Uysi',
      fecha: '24/12/12',
      hibrido: 'NSAO234BOWEQ234BKJSD1',
      superficie: '3000 ha',
      indice: '18912',
      bolsas_totales: '87',
      sembrado: true,
    },
    {
      id: 107,
      nombre: 'Lote Sjuyhjolip 76',
      fecha: '24/12/12',
      hibrido: 'NSAO234BOWEQ234BKJSD1',
      superficie: '3000 ha',
      indice: '18912',
      bolsas_totales: '87',
      sembrado: true,
    },
    {
      id: 108,
      nombre: 'Lotes tium 87',
      fecha: '24/12/12',
      hibrido: 'NSAO234BOWEQ234BKJSD1',
      superficie: '3000 ha',
      indice: '18912',
      bolsas_totales: '87',
      sembrado: true,
    },
    {
      id: 109,
      nombre: 'Nombres Lots Uysi',
      fecha: '24/12/12',
      hibrido: 'NSAO234BOWEQ234BKJSD1',
      superficie: '3000 ha',
      indice: '18912',
      bolsas_totales: '87',
      sembrado: true,
    },
    {
      id: 110,
      nombre: 'Lote Sjuyhjolip 76',
      fecha: '24/12/12',
      hibrido: 'NSAO234BOWEQ234BKJSD1',
      superficie: '3000 ha',
      indice: '18912',
      bolsas_totales: '87',
      sembrado: true,
    },
  ]
}

export {
  tableData,
  fakeRecomendacion
};